// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjdgskdv46CsyjLTsFul0j1LXTNSUDZJU',
    appId: '1:510898345493:web:60f25766fe224f35c7601c',
    messagingSenderId: '510898345493',
    projectId: 'sucasa-2d869',
    authDomain: 'sucasa-2d869.firebaseapp.com',
    storageBucket: 'sucasa-2d869.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0h8OCjrb5hT3xPe4GM-IZ4FSNYLu9yCw',
    appId: '1:510898345493:android:525df084b919c066c7601c',
    messagingSenderId: '510898345493',
    projectId: 'sucasa-2d869',
    storageBucket: 'sucasa-2d869.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjdgskdv46CsyjLTsFul0j1LXTNSUDZJU',
    appId: '1:510898345493:web:cf6c75de714ded89c7601c',
    messagingSenderId: '510898345493',
    projectId: 'sucasa-2d869',
    authDomain: 'sucasa-2d869.firebaseapp.com',
    storageBucket: 'sucasa-2d869.firebasestorage.app',
  );
}
